version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      next:
        patterns:
          - "next"
          - "eslint-config-next"
      react:
        patterns:
          - "react"
          - "@types/react"
          - "react-dom"
          - "@types/react-dom"
      tailwindcss:
        patterns:
          - "tailwindcss"
          - "@tailwindcss*"
      commitlint:
        patterns:
          - "@commitlint*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint*"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "@types/node"
        versions: ["20.x"]
